FROM golang:1.24-alpine AS builder
WORKDIR /src
COPY go.mod go.sum ab-proxy.go ./
RUN CGO_ENABLED=0 go build -o /ab-proxy .

FROM alpine:3.21
COPY --from=builder /ab-proxy /ab-proxy
ENTRYPOINT ["/ab-proxy"]
